### ISSUE TITLE
hii, i faced a lockscreen clock interface issue

### ISSUE THREAD

**Issue by Jobatphysics** [SuperiorOS/android_frameworks_base#46]
just see screenshot it's enough 
![Screenshot_20220926-114644](https://user-images.githubusercontent.com/94097278/192206562-691e8875-e220-485b-ab32-1a5be54e7110.png)

**Comment by Joker-V2** [comment]
A13 ?

**Comment by Jobatphysics** [comment]
yes sir

**Comment by Joker-V2** [comment]
Coming with all fonts ?

**Comment by Jobatphysics** [comment]
no i don't think so, it's definitely font dependent issue

**Comment by Jobatphysics** [comment]
in linotte font I'm facing this, in default it's normal as expected

**Comment by Jobatphysics** [comment]
ok so i got the issue, it's only when it's 11 hours, see it's lost now
![Uploading Screenshot_20220926-121024.png…]()

**Comment by Jobatphysics** [comment]
it's only when 11 in hours,, see 
![Uploading Screenshot_20220926-121024.png…]()

**Comment by Darkstar085** [comment]
![Screenshot_20220926-121232](https://user-images.githubusercontent.com/29405483/192210136-7649fc71-3733-4ad9-a3a3-e9c9f0786747.png)

Seems fine here..

**Comment by Jobatphysics** [comment]
it's only when 11 hours

**Comment by Joker-V2** [comment]
Ok... We will check

**Comment by Darkstar085** [comment]
Ok will look into it.. issue will b closed if it got fixed . Thnx for the report..
