### ISSUE TITLE
one-line Lockscreen clock with no notification shown on lockscreen for, don't show notifications at all at lock screen setting 

### ISSUE THREAD

**Issue by Jobatphysics** [SuperiorOS/android_frameworks_base#47]
![Screenshot_20220930-113941.png](https://user-images.githubusercontent.com/94097278/193202586-99161ed9-bf31-4f1d-9792-1310e2e8d8b3.png)![Screenshot_20220930-113949_SuperiorOS Launcher.png](https://user-images.githubusercontent.com/94097278/193202594-8cab286a-9d4b-4eff-a490-721e95320b82.png)

**Comment by Darkstar085** [comment]
Did u enabled double lined clock..??

**Comment by Jobatphysics** [comment]
definitely yes, otherwise why i will report 😅

**Comment by Jobatphysics** [comment]
![Screenshot_20220930-120225.png](https://user-images.githubusercontent.com/94097278/193205474-4e647a90-4887-4fc0-a841-7d9f4988d8c3.png) see its fine when no notification

**Comment by Darkstar085** [comment]
So in the first ss there are notifications..?? But hidden them..??

**Comment by Jobatphysics** [comment]
yes, because of setting i enabled that don't show notification at all, it's not showing notification but reducing two line clock to one line clock. which is not expected

**Comment by Darkstar085** [comment]
Thats how google made it.. Still will check if i can do any..
