### ISSUE TITLE
where are the codes of media player in the qs panel(like OxygenOS)?

### ISSUE THREAD

**Issue by Boom-Hacker** [SuperiorOS/android_frameworks_base#93]

**Comment by Darkstar085** [comment]
U high..??? We never had anything like that

**Comment by Boom-Hacker** [comment]
what???

**Comment by Boom-Hacker** [comment]
SuperiorExtended is not SuperiorOS?

**Comment by Boom-Hacker** [comment]
> U high..??? We never had anything like that

all right
btw,how can i build systemui and settings independently?

**Comment by Darkstar085** [comment]
> > U high..??? We never had anything like that
> 
> all right btw,how can i build systemui and settings independently?

Obviously u can
